CREATE TABLE notes (
  id TEXT PRIMARY KEY UNIQUE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  date_created TIMESTAMP NOT NULL,
  folder TEXT REFERENCES folders(id) ON DELETE CASCADE NOT NULL
);
